# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    git clone https://github.com/dotnet/orleans api-src
  displayName: 'Clone Orleans'

- powershell: |
    choco install docfx -y
  displayName: 'Install DocFx'

- powershell: |
    docfx src/docfx.json
    if ($lastexitcode -ne 0) {
      throw ("Error generating document")
    }
  displayName: 'docfx build'